/*===============================================================================
 05 - Magnitude Analysis
===============================================================================

Purpose:
    - To analyze the distribution and contribution of customers, products,
      and sales across various dimensions.
    - Understand which countries, categories, customers, and products
      drive the most revenue and volume.

Key Analyses:
    - Total customers by country and gender
    - Total products and average cost by category
    - Total revenue by product category
    - Customer-level revenue contribution
    - Items sold distribution by country

SQL Functions Used:
    - SUM(), AVG(), COUNT(), GROUP BY, ORDER BY

===============================================================================*/



-- Find total customers by countries
SELECT
	country,
    COUNT(customer_key) AS total_customers
FROM gold_dim_customers
GROUP BY country
ORDER BY total_customers DESC;


-- Find total customers by gender
SELECT
	gender,
    COUNT(gender) AS total_customers
FROM gold_dim_customers
GROUP BY gender
ORDER BY total_customers DESC;



-- Find total products by category
SELECT
	category,
    COUNT(product_key) AS total_products
FROM gold_dim_products
GROUP BY category
ORDER BY total_products DESC;



-- What is the average costs in each category?
SELECT 
	category,
    AVG(cost) AS avg_cost
FROM gold_dim_products
GROUP BY category
ORDER BY avg_cost DESC;



-- What is the total revenue generated for each category
SELECT
    p.category,
    SUM(f.sales_amount) AS revenue
FROM gold_fact_sales f
LEFT JOIN gold_dim_products p
	ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY revenue DESC;



-- Find total revenue generated by each customer
SELECT
	c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold_fact_sales f
LEFT JOIN gold_dim_customers c
	ON c.customer_key = f.customer_key
GROUP BY 
	c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;




-- What is the distribution of sold items across countries?
SELECT 
	c.country,
    SUM(f.quantity) AS total_items_sold
FROM gold_fact_sales f
LEFT JOIN gold_dim_customers c
	ON f.customer_key = c.customer_key
GROUP BY 
	c.country
ORDER BY total_items_sold DESC;
